apiVersion: v1
kind: ConfigMap
metadata:
  name: havuz-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "havuz-mysql"
  DB_PORT: "3306"
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_SYNC: {{ .Values.config.dbSync | quote }}
  JWT_EXPIRES_IN: {{ .Values.config.jwtExpiresIn | quote }}
  CORS_ORIGIN: {{ .Values.config.corsOrigin | quote }}
  ADMIN_EMAIL: {{ .Values.config.adminEmail | quote }}
  ADMIN_NAME: {{ .Values.config.adminName | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: havuz-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
